apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -alpha

namespace: study-flask-alpha

resources:
- ingress.yaml
- ../../bases

commonLabels:
  phase: alpha

patchesStrategicMerge:
- deployment.yaml
images:
- name: docker.io/lhj5772/lhj5772/flask_image_x86
  newTag: latest
