apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: flask
    app.kubernetes.io/part-of: study
  name: study-flask
spec:
  ports:
    - name: http
      port: 8000
      targetPort: http
  # This selector select both real and canary deployment, therefore both will be routed.
  selector:
    app.kubernetes.io/name: flask
    app.kubernetes.io/part-of: study
